"""rename all tables

Revision ID: 0f7f9da5f7b8
Revises: d2f9aff192b9
Create Date: 2023-11-28 20:05:54.056089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0f7f9da5f7b8'
down_revision: Union[str, None] = 'd2f9aff192b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from alembic import op
    from sqlalchemy.sql import text
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('lastTicketNumber', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lastTypeNumber', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Event_')),
    sa.UniqueConstraint('id', name=op.f('uq_Event__id'))
    )
    conn.execute(text("""insert into Event_ select * from Event"""))
    op.create_table('Operation_',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Operation_')),
    sa.UniqueConstraint('id', name=op.f('uq_Operation__id'))
    )
    conn.execute(text("""insert into Operation_ select * from Operation"""))
    op.create_table('Role_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Role_')),
    sa.UniqueConstraint('id', name=op.f('uq_Role__id'))
    )
    conn.execute(text("""insert into Role_ select * from Role"""))
    op.create_table('Permission_',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('operationId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['operationId'], ['Operation_.id'], name=op.f('fk_Permission__operationId_Operation_')),
    sa.ForeignKeyConstraint(['roleId'], ['Role_.id'], name=op.f('fk_Permission__roleId_Role_')),
    sa.PrimaryKeyConstraint('roleId', 'operationId', name=op.f('pk_Permission_'))
    )
    conn.execute(text("""insert into Permission_ select * from Permission"""))
    op.create_table('TicketType_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event_.id'], name=op.f('fk_TicketType__eventId_Event_')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TicketType_')),
    sa.UniqueConstraint('id', name=op.f('uq_TicketType__id'))
    )
    conn.execute(text("""insert into TicketType_ select * from TicketType"""))
    op.create_table('User_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('bossId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bossId'], ['User_.id'], name=op.f('fk_User__bossId_User_')),
    sa.ForeignKeyConstraint(['roleId'], ['Role_.id'], name=op.f('fk_User__roleId_Role_')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User_')),
    sa.UniqueConstraint('id', name=op.f('uq_User__id'))
    )
    conn.execute(text("""insert into User_ select * from User"""))
    with op.batch_alter_table('User_', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User__login'), ['login'], unique=True)

    op.create_table('Log_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('actionCode', sa.String(length=16), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('tableName', sa.String(length=16), nullable=False),
    sa.Column('recordId', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User_.id'], name=op.f('fk_Log__userId_User_')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Log_')),
    sa.UniqueConstraint('id', name=op.f('uq_Log__id'))
    )
    conn.execute(text("""insert into Log_ select * from Log"""))
    op.create_table('PermissionAccess_',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event_.id'], name=op.f('fk_PermissionAccess__eventId_Event_')),
    sa.ForeignKeyConstraint(['userId'], ['User_.id'], name=op.f('fk_PermissionAccess__userId_User_')),
    sa.PrimaryKeyConstraint('userId', 'eventId', name=op.f('pk_PermissionAccess_'))
    )
    conn.execute(text("""insert into PermissionAccess_ select * from PermissionAccess"""))
    op.create_table('Ticket_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('createdById', sa.Integer(), nullable=False),
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('scanned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=True),
    sa.Column('updatedById', sa.Integer(), nullable=True),
    sa.Column('scannedDate', sa.DateTime(), nullable=True),
    sa.Column('scannedById', sa.Integer(), nullable=True),
    sa.Column('personName', sa.String(length=256), nullable=True),
    sa.Column('personLink', sa.String(length=256), nullable=True),
    sa.Column('promocode', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['createdById'], ['User_.id'], name=op.f('fk_Ticket__createdById_User_')),
    sa.ForeignKeyConstraint(['eventId'], ['Event_.id'], name=op.f('fk_Ticket__eventId_Event_')),
    sa.ForeignKeyConstraint(['scannedById'], ['User_.id'], name=op.f('fk_Ticket__scannedById_User_')),
    sa.ForeignKeyConstraint(['typeId'], ['TicketType_.id'], name=op.f('fk_Ticket__typeId_TicketType_')),
    sa.ForeignKeyConstraint(['updatedById'], ['User_.id'], name=op.f('fk_Ticket__updatedById_User_')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Ticket_')),
    sa.UniqueConstraint('code', name=op.f('uq_Ticket__code')),
    sa.UniqueConstraint('id', name=op.f('uq_Ticket__id'))
    )
    conn.execute(text("""insert into Ticket_ select * from Ticket"""))
    op.drop_table('Role')
    op.drop_table('Event')
    op.drop_table('Operation')
    op.drop_table('TicketType')
    op.drop_table('Ticket')
    op.drop_table('Permission')
    op.drop_table('PermissionAccess')
    op.drop_table('Log')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_login')

    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('login', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('roleId', sa.INTEGER(), nullable=False),
    sa.Column('bossId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bossId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('ix_User_login', ['login'], unique=False)

    op.create_table('Log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('actionCode', sa.VARCHAR(length=16), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('userName', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tableName', sa.VARCHAR(length=16), nullable=False),
    sa.Column('recordId', sa.INTEGER(), nullable=False),
    sa.Column('changes', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('PermissionAccess',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('eventId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('userId', 'eventId')
    )
    op.create_table('Permission',
    sa.Column('roleId', sa.INTEGER(), nullable=False),
    sa.Column('operationId', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['operationId'], ['Operation.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('roleId', 'operationId')
    )
    op.create_table('Ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('createdDate', sa.DATETIME(), nullable=False),
    sa.Column('createdById', sa.INTEGER(), nullable=False),
    sa.Column('eventId', sa.INTEGER(), nullable=False),
    sa.Column('typeId', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('scanned', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('updatedDate', sa.DATETIME(), nullable=True),
    sa.Column('updatedById', sa.INTEGER(), nullable=True),
    sa.Column('scannedDate', sa.DATETIME(), nullable=True),
    sa.Column('scannedById', sa.INTEGER(), nullable=True),
    sa.Column('personName', sa.VARCHAR(length=256), nullable=True),
    sa.Column('personLink', sa.VARCHAR(length=256), nullable=True),
    sa.Column('promocode', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['createdById'], ['User.id'], ),
    sa.ForeignKeyConstraint(['eventId'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['scannedById'], ['User.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['TicketType.id'], ),
    sa.ForeignKeyConstraint(['updatedById'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('TicketType',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('eventId', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Operation',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('lastTicketNumber', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('lastTypeNumber', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('Ticket_')
    op.drop_table('PermissionAccess_')
    op.drop_table('Log_')
    with op.batch_alter_table('User_', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User__login'))

    op.drop_table('User_')
    op.drop_table('TicketType_')
    op.drop_table('Permission_')
    op.drop_table('Role_')
    op.drop_table('Operation_')
    op.drop_table('Event_')
    # ### end Alembic commands ###
