"""v5

Revision ID: 906b0f62de38
Revises: 7e03beaed783
Create Date: 2026-03-27 21:29:40.495180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906b0f62de38'
down_revision: Union[str, None] = '7e03beaed783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ticket', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
