"""v6

Revision ID: 84dd74644c57
Revises: 906b0f62de38
Create Date: 2026-03-30 11:56:21.931699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dd74644c57'
down_revision: Union[str, None] = '906b0f62de38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('TicketType', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TicketType', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('Log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'User', ['userId'], ['id'])

    # ### end Alembic commands ###
